# Generated by Django 5.1.3 on 2024-11-27 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=255)),
                ('vyhry', models.IntegerField(default=0)),
                ('prohry', models.IntegerField(default=0)),
                ('remizy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hrac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=255)),
                ('prijmeni', models.CharField(max_length=255)),
                ('goly', models.IntegerField(default=0)),
                ('asistence', models.IntegerField(default=0)),
                ('tym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotbal_liga.tym')),
            ],
        ),
        migrations.CreateModel(
            name='Zapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('goly_tym_a', models.IntegerField(default=0)),
                ('goly_tym_b', models.IntegerField(default=0)),
                ('tym_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapasy_tym_a', to='fotbal_liga.tym')),
                ('tym_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapasy_tym_b', to='fotbal_liga.tym')),
            ],
        ),
        migrations.CreateModel(
            name='StatistikyZapasu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goly', models.IntegerField(default=0)),
                ('asistence', models.IntegerField(default=0)),
                ('zlte_karty', models.IntegerField(default=0)),
                ('cervene_karty', models.IntegerField(default=0)),
                ('hrac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotbal_liga.hrac')),
                ('zapas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotbal_liga.zapas')),
            ],
        ),
    ]
